import type { Created, IsoTimestamp, JsonObject, Uuid } from "@/types/common";
import type { AuditActorType } from "@/domain/taxonomy/audit-actor-type";
import type { AuditEventType } from "@/domain/taxonomy/audit-event-type";
import type { AppliedRuleVersion } from "@/domain/rules/outcome";

/**
 * Every state change — `ERD.md` §10.2. **APPEND-ONLY**.
 *
 * **Who, what, when, before, after, and which rule version applied.** Written by
 * a `security definer` trigger on every tenant table, never by a user statement
 * — so a user can neither forge nor suppress a row, and **coverage is not a
 * checklist item a builder can miss** (Rules 12.3, 12.4).
 *
 * If the audit insert fails, the surrounding transaction fails with it: an
 * unauditable state change does not happen.
 *
 * Immutability is enforced three ways — no UPDATE/DELETE policy,
 * `revoke update, delete from authenticated`, and a `before update or delete`
 * trigger that raises unconditionally, which is the only one of the three that
 * also stops the service-role key. **No role, including P6, may edit or delete
 * an audit event** (Rules 1.21, 12.4).
 *
 * `audit_event` is not deleted at all. The export at `/audit` is how it leaves
 * the system, every export is scoped to what the requester could already open
 * individually (Rule 12.17), and the export is **itself an audited act**
 * (Rule 12.18).
 */
export interface AuditEvent extends Created {
  readonly id: Uuid;
  /** Total order. `generated by default as identity`. */
  readonly sequenceNo: number;
  /** Null for platform-level events. */
  readonly organizationId: Uuid | null;
  /** **Who.** */
  readonly actorUserId: Uuid | null;
  /**
   * Whether the actor was a person, a scheduled job or an integration. T-60.
   *
   * **Automated pipeline steps write events exactly as human actions do**,
   * identified as the step that ran and carrying the model or rule version used
   * (Rule 12.5). **Platform actions are distinguishable from a member's**
   * (Rule 12.7).
   */
  readonly actorType: AuditActorType;
  /** For non-user actors: which job, which integration. */
  readonly actorLabel: string | null;
  /** **What.** T-43. */
  readonly eventType: AuditEventType;
  readonly entityTable: string;
  readonly entityId: Uuid;
  /** **When.** Carries a zone (Rule 12.20). */
  readonly occurredAt: IsoTimestamp;
  readonly recordedAt: IsoTimestamp;
  /** **Before.** Null on insert. */
  readonly beforeState: JsonObject | null;
  /** **After.** Null on a delete that a guard permitted. */
  readonly afterState: JsonObject | null;
  /** Diff, unchanged columns dropped. */
  readonly changedFields: readonly string[] | null;
  /** **Which rule version applied.** */
  readonly governingRuleVersionId: Uuid | null;
  /** Full applied set where more than one governed. */
  readonly ruleVersionsApplied: readonly AppliedRuleVersion[] | null;
  /** Ties one user action across every row and log line it produced. */
  readonly correlationId: string | null;
  readonly requestId: string | null;
  readonly ipAddress: string | null;
  readonly userAgent: string | null;
  /**
   * Supplied on overrides and refusals.
   *
   * **Denials are audited because attempts are evidence** (Rule 12.6): a blocked
   * air-transport selection, a rejected P5 write and a prohibited-activity
   * attempt are all written here, not merely refused.
   */
  readonly reason: string | null;
}
