"use client";

import Link from "next/link";
import { useState, type ReactElement, type ReactNode } from "react";
import { Download, Minus, Plus, Printer } from "lucide-react";

import { ACTION_BUTTON_CLASS, ICON_BUTTON_CLASS } from "@/components/page";
import { InlineActionError } from "@/components/extraction-review/review-controls";
import { INTENT_SURFACE_CLASSES } from "@/components/status/intent-classes";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import type { ActionResult } from "@/lib/action-result";
import { cn } from "@/lib/utils";

/**
 * `DocumentViewer` — `UX_SPEC.md` §2.8, §3.14.
 *
 * A paged canvas on a muted backdrop, a toolbar with **Print**, **Download
 * PDF**, page navigation and zoom, and a metadata strip: document type,
 * generated at, generated by, the record it belongs to, and the render
 * instance ID in mono.
 *
 * **Print and Download are never disabled, for any role that can reach the
 * route — P5 included** (Rule 5.27). Reading and printing evidence is the
 * auditor's whole task, so neither control consults a role at all.
 *
 * **Printing is a real browser print** against the print stylesheet in
 * `globals.css`: Letter, no app chrome, black on white. Only the element marked
 * `data-print-document` prints. **A voided, superseded or draft render carries
 * its marking inside that element**, so the marking survives the paper — it is
 * part of the page, never an on-screen overlay (§3.14). Every print is recorded
 * first: `onPrint` writes the audit row, and a print that could not be recorded
 * does not start (BR §12).
 *
 * **A render is immutable** (Rules 4.20, 5.12). Nothing here edits one; the
 * canvas is whatever the route composed from the render's own frozen rows.
 */

export interface DocumentViewerMetadata {
  /** T-38's label. */
  readonly typeLabel: string;
  /** Already formatted, with the zone beside it (Rule 4.29). */
  readonly generatedAt: string;
  readonly generatedBy: string;
  /** The record the document belongs to, and a link for roles that can open it. */
  readonly source: { readonly label: string; readonly href: string | null };
  /** `document_render.id`, printed in the footer and copyable here. */
  readonly renderId: string;
  /** T-39's label for the stored status. */
  readonly statusLabel: string;
}

/** What the Download action hands back: the stored bytes, as issued. */
export interface DownloadedDocument {
  readonly fileName: string;
  readonly contentType: string;
  /** Base64 — Server Action results travel as JSON. */
  readonly base64: string;
}

export interface DocumentViewerProps {
  readonly metadata: DocumentViewerMetadata;
  /** The render's page count; null when the render did not record one. */
  readonly pageCount: number | null;
  /** Records the print (T-43 `document.reprinted`) before the browser prints. */
  readonly onPrint: () => Promise<ActionResult<unknown>>;
  /** Streams the stored bytes. A render with none says so, stated. */
  readonly onDownload: () => Promise<ActionResult<DownloadedDocument>>;
  /** The composed page. Marking for void, supersession or draft belongs inside it. */
  readonly children: ReactNode;
  /** A preview inside another page — `/containers/[id]`'s Label tab. */
  readonly embedded?: boolean;
  readonly className?: string;
}

const ZOOM_STEPS = [0.75, 1, 1.25, 1.5] as const;
const DEFAULT_ZOOM_INDEX = 1;

function saveBytes(file: DownloadedDocument): void {
  const binary = atob(file.base64);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }
  const url = URL.createObjectURL(
    new Blob([bytes], { type: file.contentType }),
  );
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = file.fileName;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function DocumentViewer({
  metadata,
  pageCount,
  onPrint,
  onDownload,
  children,
  embedded = false,
  className,
}: DocumentViewerProps): ReactElement {
  const [zoomIndex, setZoomIndex] = useState(DEFAULT_ZOOM_INDEX);
  const [busy, setBusy] = useState<"print" | "download" | null>(null);
  const [error, setError] = useState<string | null>(null);
  const zoom = ZOOM_STEPS[zoomIndex] ?? 1;

  async function print(): Promise<void> {
    if (busy !== null) return;
    setBusy("print");
    setError(null);
    try {
      const recorded = await onPrint();
      if (!recorded.ok) {
        setError(recorded.error.message);
        return;
      }
      window.print();
    } finally {
      setBusy(null);
    }
  }

  async function download(): Promise<void> {
    if (busy !== null) return;
    setBusy("download");
    setError(null);
    try {
      const result = await onDownload();
      if (!result.ok) {
        setError(result.error.message);
        return;
      }
      saveBytes(result.data);
    } finally {
      setBusy(null);
    }
  }

  return (
    <div
      data-document-viewer="true"
      data-embedded={embedded ? "true" : "false"}
      className={cn("flex flex-col gap-4", className)}
    >
      <div
        data-print-hide="true"
        className="flex flex-wrap items-center justify-between gap-2"
      >
        <div className="flex flex-wrap items-center gap-2">
          {/* Never disabled, for any role (Rule 5.27). `aria-busy` while the
              print is recorded; the button stays in the tab order. */}
          <Button
            type="button"
            size="lg"
            data-document-print="true"
            aria-busy={busy === "print" ? "true" : undefined}
            onClick={() => void print()}
            className={ACTION_BUTTON_CLASS}
          >
            <Printer aria-hidden="true" />
            Print
          </Button>
          <Button
            type="button"
            variant="outline"
            size="lg"
            data-document-download="true"
            aria-busy={busy === "download" ? "true" : undefined}
            onClick={() => void download()}
            className={ACTION_BUTTON_CLASS}
          >
            <Download aria-hidden="true" />
            Download PDF
          </Button>
        </div>
        <div className="flex items-center gap-2">
          <Button
            type="button"
            variant="ghost"
            size="icon"
            aria-label="Zoom out"
            aria-disabled={zoomIndex === 0 ? "true" : undefined}
            onClick={() => setZoomIndex((index) => Math.max(0, index - 1))}
            className={ICON_BUTTON_CLASS}
          >
            <Minus aria-hidden="true" />
          </Button>
          <span
            data-document-zoom="true"
            className="tabular min-w-12 text-center text-label"
          >
            {`${Math.round(zoom * 100)}%`}
          </span>
          <Button
            type="button"
            variant="ghost"
            size="icon"
            aria-label="Zoom in"
            aria-disabled={
              zoomIndex === ZOOM_STEPS.length - 1 ? "true" : undefined
            }
            onClick={() =>
              setZoomIndex((index) =>
                Math.min(ZOOM_STEPS.length - 1, index + 1),
              )
            }
            className={ICON_BUTTON_CLASS}
          >
            <Plus aria-hidden="true" />
          </Button>
          <span data-document-pages="true" className="text-caption">
            {pageCount === null ? "Page 1" : `Page 1 of ${pageCount}`}
          </span>
        </div>
      </div>

      {error !== null ? (
        <div data-print-hide="true">
          <InlineActionError
            message={error}
            dataAttribute="data-document-action-error"
          />
        </div>
      ) : null}

      <div
        data-document-backdrop="true"
        className="overflow-auto rounded-lg bg-muted p-4 md:p-8"
      >
        <article
          data-print-document="true"
          aria-label={`${metadata.typeLabel} ${metadata.renderId}`}
          style={{ zoom }}
          className="mx-auto flex aspect-[8.5/11] w-full max-w-3xl flex-col gap-6 rounded-md border border-border bg-background p-6 text-foreground md:p-12"
        >
          {children}
          <footer className="mt-auto flex flex-wrap justify-between gap-2 border-t border-border pt-2 text-caption">
            <span>{metadata.typeLabel}</span>
            <span className="text-mono">{metadata.renderId}</span>
          </footer>
        </article>
      </div>

      <dl
        data-document-metadata="true"
        data-print-hide="true"
        className="grid grid-cols-1 gap-x-8 gap-y-2 sm:grid-cols-2"
      >
        <MetaRow label="Document type" value={metadata.typeLabel} />
        <MetaRow label="Status" value={metadata.statusLabel} />
        <MetaRow label="Generated at" value={metadata.generatedAt} />
        <MetaRow label="Generated by" value={metadata.generatedBy} />
        <div className="flex flex-col gap-1">
          <dt className="text-caption text-muted-foreground">Source record</dt>
          <dd className="text-body">
            {metadata.source.href === null ? (
              metadata.source.label
            ) : (
              <Link
                href={metadata.source.href}
                data-document-source="true"
                className="inline-flex min-h-11 items-center underline underline-offset-4"
              >
                {metadata.source.label}
              </Link>
            )}
          </dd>
        </div>
        <MetaRow label="Render instance" value={metadata.renderId} mono />
      </dl>
    </div>
  );
}

function MetaRow({
  label,
  value,
  mono = false,
}: {
  readonly label: string;
  readonly value: string;
  readonly mono?: boolean;
}): ReactElement {
  return (
    <div className="flex flex-col gap-1">
      <dt className="text-caption text-muted-foreground">{label}</dt>
      <dd className={cn(mono ? "text-mono break-all" : "text-body")}>
        {value}
      </dd>
    </div>
  );
}

/**
 * The marking a render that is not the live document carries **on the page**
 * — voided, superseded or draft (Rules 5.13–5.15, 5.28; T-39). It prints,
 * because it is inside the printed element.
 */
export function DocumentStatusMarking({
  status,
  statusLabel,
  detail,
  supersededBy,
}: {
  /** T-39 as stored. */
  readonly status: string;
  readonly statusLabel: string;
  readonly detail: string | null;
  readonly supersededBy?: { readonly href: string; readonly label: string };
}): ReactElement | null {
  if (status === "issued") return null;
  const intent = status === "voided" ? "critical" : "attention";
  const heading =
    status === "voided"
      ? `${statusLabel} — this document is not valid`
      : status === "superseded"
        ? `${statusLabel} — no longer valid`
        : `${statusLabel} — not valid, not issued`;
  return (
    <div
      role="note"
      data-document-marking={status}
      className={cn(
        "flex flex-col gap-1 rounded-md border-2 p-4",
        INTENT_SURFACE_CLASSES[intent],
      )}
    >
      <span className="text-h2">{heading}</span>
      {detail === null ? null : <span className="text-body">{detail}</span>}
      {supersededBy === undefined ? null : (
        <Link
          href={supersededBy.href}
          className="inline-flex min-h-11 items-center text-label underline underline-offset-4"
        >
          {supersededBy.label}
        </Link>
      )}
    </div>
  );
}

/** Loading — the page's aspect ratio, and the words §2.8 asks for. */
export function DocumentViewerSkeleton(): ReactElement {
  return (
    <div data-document-viewer="loading" className="flex flex-col gap-4">
      <div className="flex gap-2">
        <Skeleton className="h-11 w-28 rounded-md" />
        <Skeleton className="h-11 w-40 rounded-md" />
      </div>
      <div className="rounded-lg bg-muted p-4 md:p-8">
        <div className="mx-auto flex aspect-[8.5/11] w-full max-w-3xl items-center justify-center rounded-md border border-border bg-background">
          <span className="text-body text-muted-foreground">
            Preparing document
          </span>
        </div>
      </div>
    </div>
  );
}
